# Generated by Django 3.1.4 on 2021-01-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('link', models.CharField(max_length=300)),
                ('acess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cateogies')),
            ],
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
